package com.portfolio.recall.rag;

import static org.assertj.core.api.Assertions.assertThat;

import com.portfolio.recall.config.RecallProperties;
import com.portfolio.recall.search.RetrievedChunk;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Adaptive context sizing (docs/adr/0013), and above all its agreement with the calibrator.
 *
 * <p>The coverage guarantee is a property of one procedure: calibrate a quantile on held-out
 * queries, then apply <em>the same</em> rule at serving time. Python picks the quantile;
 * Java decides how many passages a live query gets. If those two disagree about what the
 * quantile means, alpha is decoration — the system would carry a certificate for a rule it
 * does not run.
 *
 * <p>So the central test replays golden vectors generated by {@code eval/conformal.py} at a
 * known threshold and asserts identical set sizes. The vectors deliberately include the
 * awkward shapes — one dominant passage, a flat tie, all-negative logits, a single candidate
 * — and every case sits at least 1e-9 away from the inclusion boundary, so a last-ulp
 * difference between the two {@code exp} implementations cannot flip an answer.
 */
class ConformalSetSizerTest {

    /** Produced by eval/conformal.py at alpha = 0.10, temperature = 1.0, n = 800. */
    private static final double GOLDEN_THRESHOLD = 0.5286119812181718;

    private static ConformalSetSizer sizer(boolean enabled, double threshold, double temperature,
                                           int maxK, int topK) {
        RecallProperties props = new RecallProperties(
                null, null, null, null,
                new RecallProperties.Retrieval(50, topK, 60),
                null, null,
                new RecallProperties.Rag(
                        new RecallProperties.Rag.Judge(false, 1),
                        new RecallProperties.Rag.Sufficiency(false, 0.35, 1),
                        new RecallProperties.Rag.Conformal(enabled, 0.10, threshold,
                                temperature, maxK)),
                null);
        return new ConformalSetSizer(props, new SimpleMeterRegistry());
    }

    private static ConformalSetSizer calibrated() {
        return sizer(true, GOLDEN_THRESHOLD, 1.0, 100, 8);
    }

    /** Reranked chunks carrying the given scores, in the order supplied. */
    private static List<RetrievedChunk> ranked(double... scores) {
        List<RetrievedChunk> chunks = new ArrayList<>(scores.length);
        for (int i = 0; i < scores.length; i++) {
            chunks.add(new RetrievedChunk("chunk-" + i, "doc-" + i, i, "content " + i,
                    "test", "en", scores[i]));
        }
        return chunks;
    }

    @Nested
    @DisplayName("agrees with the Python calibrator")
    class GoldenVectors {

        private void assertSize(int expected, double... scores) {
            assertThat(calibrated().size(ranked(scores)))
                    .as("scores %s", java.util.Arrays.toString(scores))
                    .isEqualTo(expected);
        }

        @Test
        @DisplayName("hand-picked shapes: dominant, flat, negative, tied, singleton")
        void edgeShapes() {
            assertSize(1, 10.0, 1.0, 0.5, 0.1, 0.0);
            assertSize(4, 0.2, 0.19, 0.18, 0.17, 0.16, 0.15);
            assertSize(1, 3.0, 2.5, 1.0, 0.2);
            assertSize(1, -1.0, -2.0, -3.0);
            assertSize(3, 0.0, 0.0, 0.0, 0.0);
            assertSize(1, 5.0);
        }

        @Test
        @DisplayName("randomly generated score profiles")
        void randomProfiles() {
            assertSize(1, 4.565677, 4.004044, 1.203501, 0.927092, 0.691014, 0.273596, -1.065086);
            assertSize(3, 2.327879, 2.082064, 2.045292, 1.193429, 0.466179, 0.378049, 0.371034,
                    0.292328, -1.565706, -1.654151, -1.859524, -1.930819);
            assertSize(1, 7.504807, 2.056478, 0.576293, 0.263916, 0.019551, -0.183291, -0.522587,
                    -0.633274, -2.219263);
            assertSize(1, 0.419173, -1.069097, -1.719599);
            assertSize(2, 2.166895, 1.860171, 0.773053, 0.155565, -0.239316, -0.465664, -0.69162,
                    -2.356487, -5.326175);
            assertSize(1, 4.770728, 0.524554, 0.064116, -0.664532, -0.849502);
            assertSize(1, 2.391052, 1.325254, 0.371253, 0.041954, -0.128677, -3.532411);
            assertSize(1, 2.643379, -0.960449, -3.360804, -3.77729);
            assertSize(1, 4.67488, -0.253449);
            assertSize(4, 0.660169, 0.457363, 0.428627, 0.400789, 0.095027, 0.014098, 0.003473,
                    -0.522337, -0.968956, -2.91059);
            assertSize(1, 3.390397, 1.54235, 1.514102, 1.194389, 0.185057, -0.639207, -3.214939);
            assertSize(1, 4.654588, 3.571974, 0.346738, -0.194289, -0.24425, -0.760455, -1.691511,
                    -2.948554, -3.229008, -3.623318);
            assertSize(1, 3.779924, 0.278538, 0.047883, -0.096617, -0.179485, -1.063998, -1.631784,
                    -8.79501);
            assertSize(2, 0.668901, -0.05691, -0.173395, -0.669973, -1.767961);
            assertSize(1, 2.564827, 1.450101, 1.07328, 0.000801, -3.462482, -3.623471, -4.680276,
                    -5.771396);
            assertSize(1, 3.451753, 1.195718, 0.794682, 0.274709, -0.078601, -0.472272, -0.619882,
                    -1.460382, -1.689251, -1.77017, -2.696757, -3.644469);
            assertSize(1, 2.985563, 0.929967, 0.26422, -0.767081, -2.031139, -3.879552, -5.209336);
            assertSize(1, 3.391124, 2.271434, 1.55485, -1.25865);
        }
    }

    @Nested
    @DisplayName("sizing behaviour")
    class Behaviour {

        @Test
        @DisplayName("spends more context on an ambiguous retrieval than a confident one")
        void adaptsToConfidence() {
            // The behaviour a fixed top-K cannot have. Flat scores mean the reranker has no
            // opinion, which is exactly when truncating is most likely to drop the answer.
            int confident = calibrated().size(ranked(10.0, 1.0, 0.5, 0.2, 0.1, 0.0));
            int ambiguous = calibrated().size(ranked(0.2, 0.19, 0.18, 0.17, 0.16, 0.15));
            assertThat(confident).isLessThan(ambiguous);
        }

        @Test
        @DisplayName("never returns an empty context for a non-empty candidate list")
        void neverEmpty() {
            // The first passage's exclusive prefix mass is zero, so it always qualifies —
            // even at threshold 0, where every later passage is excluded.
            assertThat(sizer(true, 0.0, 1.0, 100, 8).size(ranked(1.0, 1.0, 1.0))).isEqualTo(1);
            assertThat(calibrated().size(List.of())).isZero();
        }

        @Test
        @DisplayName("a threshold of 1 keeps every candidate")
        void thresholdOneKeepsEverything() {
            assertThat(sizer(true, 1.0, 1.0, 100, 8).size(ranked(5.0, 1.0, 0.5, 0.1)))
                    .isEqualTo(4);
        }

        @Test
        @DisplayName("survives scores that would overflow a naive softmax")
        void hugeScoresDoNotOverflow() {
            // exp(800) is infinity; the max-shift is what keeps this finite.
            assertThat(calibrated().size(ranked(800.0, 799.0, 10.0))).isBetween(1, 3);
            assertThat(calibrated().size(ranked(-800.0, -900.0))).isBetween(1, 2);
        }

        @Test
        @DisplayName("a lower temperature sharpens the distribution and shortens the context")
        void temperatureSharpens() {
            double[] scores = {2.0, 1.6, 1.2, 0.9, 0.5, 0.1};
            int sharp = sizer(true, GOLDEN_THRESHOLD, 0.25, 100, 8).size(ranked(scores));
            int soft = sizer(true, GOLDEN_THRESHOLD, 4.0, 100, 8).size(ranked(scores));
            assertThat(sharp).isLessThan(soft);
        }

        @Test
        @DisplayName("the hard cap truncates a certified set and says so")
        void capBinds() {
            SimpleMeterRegistry meters = new SimpleMeterRegistry();
            RecallProperties props = new RecallProperties(
                    null, null, null, null,
                    new RecallProperties.Retrieval(50, 8, 60), null, null,
                    new RecallProperties.Rag(
                            new RecallProperties.Rag.Judge(false, 1),
                            new RecallProperties.Rag.Sufficiency(false, 0.35, 1),
                            new RecallProperties.Rag.Conformal(true, 0.10, 0.99, 1.0, 2)),
                    null);
            ConformalSetSizer capped = new ConformalSetSizer(props, meters);
            assertThat(capped.size(ranked(0.1, 0.1, 0.1, 0.1, 0.1, 0.1))).isEqualTo(2);
            assertThat(meters.counter("recall.rag.context.capped").count()).isEqualTo(1.0);
        }
    }

    @Nested
    @DisplayName("falls back safely")
    class Fallback {

        @Test
        @DisplayName("disabled, it is exactly the old fixed top-K")
        void disabledMeansTopK() {
            ConformalSetSizer off = sizer(false, GOLDEN_THRESHOLD, 1.0, 100, 8);
            assertThat(off.enabled()).isFalse();
            assertThat(off.size(ranked(IntStream.range(0, 20).mapToDouble(i -> 20.0 - i)
                    .toArray()))).isEqualTo(8);
            assertThat(off.size(ranked(1.0, 2.0))).isEqualTo(2);
        }

        @Test
        @DisplayName("an uncalibrated threshold disables sizing instead of guessing")
        void uncalibratedIsRefused() {
            // -1 is the shipped default: no certificate exists yet, so the pipeline must
            // behave exactly as it did before rather than pretend to a guarantee.
            ConformalSetSizer unset = sizer(true, -1.0, 1.0, 100, 8);
            assertThat(unset.enabled()).isFalse();
            assertThat(unset.size(ranked(10.0, 1.0, 0.5, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0)))
                    .isEqualTo(8);
            assertThat(sizer(true, 1.5, 1.0, 100, 8).enabled()).isFalse();
        }

        @Test
        @DisplayName("a non-positive temperature falls back to 1.0 rather than dividing by zero")
        void degenerateTemperature() {
            assertThat(sizer(true, GOLDEN_THRESHOLD, 0.0, 100, 8).size(ranked(10.0, 1.0, 0.5)))
                    .isEqualTo(calibrated().size(ranked(10.0, 1.0, 0.5)));
        }
    }
}
