package com.portfolio.recall.rag;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import com.portfolio.recall.config.RecallProperties;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * The coverage-certificate monitor (docs/adr/0016), and above all its agreement with
 * {@code eval/sequential.py}.
 *
 * <p>An anytime-valid interval is worth exactly what its implementation is worth. A port
 * that is subtly wrong still produces a plausible-looking interval and a plausible-looking
 * alarm rate, and nothing about the output would reveal it — which is the failure mode this
 * repository exists to catch. So the streams below are generated by the Python
 * implementation and embedded verbatim rather than regenerated here: Java's RNG cannot
 * reproduce Python's Mersenne Twister, and a test that generated its own data would be
 * pinning the port against itself.
 *
 * <p>What is pinned: the interval bounds after the whole stream, and the exact query at
 * which the alarm fires. The second is the stronger assertion — it is a statement about
 * every prefix of the stream, not just the end.
 */
class CoverageMonitorTest {

    /** The coverage level being defended, matching the golden vectors. */
    private static final double ALPHA = 0.10;

    /** 44 misses in 400. Generated by eval/sequential.py, seed 7. */
    private static final String ON_TARGET =
            "000100101011000000000100000000000110000000000000000000001000000000000010" +
            "000000100010000010000000000000000010000000010000000011000110001000000000" +
            "001000001000010000000000000000000001100000000000000000001000000000000000" +
            "000000000001000000000000000000000000010010000000000000000000000000000000" +
            "000000101000000000000000000000010010001000001000000000001100100010100000" +
            "0000001000000001010000000000000000000010";

    /** 138 misses in 400. Generated by eval/sequential.py, seed 11. */
    private static final String DRIFTED =
            "000000100011100100001101111000000001000011110000001100001001110011110100" +
            "101010110010100010110111101000000011001100100001101010011011000101110110" +
            "010000001110001000101000000000000000000010000000001010010000111011000010" +
            "100000011000001101100010001101001011010111000000010110011100000001001000" +
            "000000010000100000100110000101011011000000011010000010001000010001000000" +
            "0100001010000110010111010010101100000110";

    private static CoverageMonitor monitor(int warmup) {
        return monitor(warmup, true, true);
    }

    private static CoverageMonitor monitor(int warmup, boolean monitorEnabled, boolean sizing) {
        RecallProperties props = new RecallProperties(
                null, null, null, null,
                new RecallProperties.Retrieval(50, 8, 60),
                null, null,
                new RecallProperties.Rag(
                        new RecallProperties.Rag.Judge(false, 1),
                        new RecallProperties.Rag.Sufficiency(false, 0.35, 1),
                        new RecallProperties.Rag.Conformal(sizing, ALPHA, 0.5, 1.0, 12,
                                monitorEnabled, 0.05, warmup)),
                null);
        return new CoverageMonitor(props, new SimpleMeterRegistry());
    }

    private static void feed(CoverageMonitor monitor, String bits) {
        for (int i = 0; i < bits.length(); i++) {
            monitor.observe(verdict(bits.charAt(i) == '1'));
        }
    }

    /** A miss is UNSUPPORTED; anything else counts as covered. */
    private static Judgment verdict(boolean miss) {
        return miss
                ? Judgment.Verdict.UNSUPPORTED.toJudgment()
                : Judgment.Verdict.SUPPORTED.toJudgment();
    }

    /** Queries consumed before the alarm latched, or -1 if it never did. */
    private static int breachStep(String bits) {
        CoverageMonitor monitor = monitor(0);
        for (int i = 0; i < bits.length(); i++) {
            monitor.observe(verdict(bits.charAt(i) == '1'));
            if (monitor.alarming()) {
                return i + 1;
            }
        }
        return -1;
    }

    @Nested
    @DisplayName("agreement with eval/sequential.py")
    class Agreement {

        @Test
        @DisplayName("the interval matches the Python confidence sequence exactly")
        void boundsMatchPython() {
            CoverageMonitor onTarget = monitor(0);
            feed(onTarget, ON_TARGET);
            assertThat(onTarget.miscoverage()).isEqualTo(0.11, within(1e-12));
            assertThat(onTarget.lower()).isEqualTo(0.0775, within(1e-12));
            assertThat(onTarget.upper()).isEqualTo(0.1725, within(1e-12));

            CoverageMonitor drifted = monitor(0);
            feed(drifted, DRIFTED);
            assertThat(drifted.miscoverage()).isEqualTo(0.345, within(1e-12));
            assertThat(drifted.lower()).isEqualTo(0.2525, within(1e-12));
            assertThat(drifted.upper()).isEqualTo(0.4375, within(1e-12));
        }

        @Test
        @DisplayName("a stream that never misses, and one that always does")
        void degenerateStreamsMatchPython() {
            CoverageMonitor perfect = monitor(0);
            feed(perfect, "0".repeat(200));
            assertThat(perfect.lower()).isEqualTo(0.0025, within(1e-12));
            assertThat(perfect.upper()).isEqualTo(0.0325, within(1e-12));

            CoverageMonitor always = monitor(0);
            feed(always, "1".repeat(200));
            assertThat(always.lower()).isEqualTo(0.9675, within(1e-12));
            assertThat(always.upper()).isEqualTo(0.9975, within(1e-12));
        }

        @Test
        @DisplayName("the alarm fires on the same query Python's bound crosses alpha")
        void breachStepMatchesPython() {
            // A statement about every prefix, not just the end: if the stake schedule or the
            // variance estimate drifted from the Python by even a little, these would move.
            assertThat(breachStep(DRIFTED)).isEqualTo(43);
            assertThat(breachStep("1".repeat(200))).isEqualTo(3);
            assertThat(breachStep(ON_TARGET)).isEqualTo(-1);
            assertThat(breachStep("0".repeat(200))).isEqualTo(-1);
        }
    }

    @Nested
    @DisplayName("what the alarm means")
    class AlarmSemantics {

        @Test
        @DisplayName("a system meeting its promise never alarms")
        void onTargetIsQuiet() {
            CoverageMonitor monitor = monitor(0);
            feed(monitor, ON_TARGET);
            assertThat(monitor.alarming()).isFalse();
            assertThat(monitor.overCovering()).isFalse();
        }

        @Test
        @DisplayName("covering better than promised is reported, not alarmed on")
        void overCoverageIsNotAnIncident() {
            // Conformal prediction is conservative by construction, so this is the ordinary
            // state of a healthy deployment. A two-sided rule would page somebody for it.
            CoverageMonitor monitor = monitor(0);
            feed(monitor, "0".repeat(200));
            assertThat(monitor.alarming()).isFalse();
            assertThat(monitor.overCovering()).isTrue();
        }

        @Test
        @DisplayName("missing far more often than promised alarms")
        void underCoverageAlarms() {
            CoverageMonitor monitor = monitor(0);
            feed(monitor, DRIFTED);
            assertThat(monitor.alarming()).isTrue();
            assertThat(monitor.overCovering()).isFalse();
        }

        @Test
        @DisplayName("the alarm latches — later good queries do not unring it")
        void alarmLatches() {
            CoverageMonitor monitor = monitor(0);
            feed(monitor, DRIFTED);
            assertThat(monitor.alarming()).isTrue();
            feed(monitor, "0".repeat(2000));         // a long, flawless recovery
            assertThat(monitor.alarming())
                    .as("the sequence is valid at every sample size; the evidence still exists")
                    .isTrue();
        }

        @Test
        @DisplayName("PARTIAL is not counted as a coverage failure")
        void partialIsNotAMiss() {
            // The passages did carry something the answer stood on. Counting it as a miss
            // would inflate the rate the certificate is held to and manufacture alarms.
            CoverageMonitor monitor = monitor(0);
            for (int i = 0; i < 300; i++) {
                monitor.observe(Judgment.Verdict.PARTIAL.toJudgment());
            }
            assertThat(monitor.miscoverage()).isZero();
            assertThat(monitor.alarming()).isFalse();
        }
    }

    @Nested
    @DisplayName("staying quiet when it should")
    class Restraint {

        @Test
        @DisplayName("warmup holds the alarm back without discarding the evidence")
        void warmupDelaysButDoesNotDiscard() {
            CoverageMonitor monitor = monitor(100);
            feed(monitor, DRIFTED.substring(0, 60));
            assertThat(monitor.alarming())
                    .as("breach is at query 43, but warmup is 100")
                    .isFalse();
            feed(monitor, DRIFTED.substring(60, 120));
            assertThat(monitor.alarming())
                    .as("past warmup, the evidence collected during it still counts")
                    .isTrue();
            assertThat(monitor.observedCount()).isEqualTo(120);
        }

        @Test
        @DisplayName("it observes nothing when sizing is off")
        void inertWithoutACertificate() {
            // Monitoring a certificate that was never issued is noise.
            CoverageMonitor monitor = monitor(0, true, false);
            assertThat(monitor.enabled()).isFalse();
            feed(monitor, DRIFTED);
            assertThat(monitor.observedCount()).isZero();
            assertThat(monitor.alarming()).isFalse();
        }

        @Test
        @DisplayName("it observes nothing when monitoring is off")
        void inertWhenDisabled() {
            CoverageMonitor monitor = monitor(0, false, true);
            assertThat(monitor.enabled()).isFalse();
            feed(monitor, DRIFTED);
            assertThat(monitor.observedCount()).isZero();
        }

        @Test
        @DisplayName("a null judgment is ignored rather than counted as covered")
        void nullJudgmentIsNotAnObservation() {
            // Judging is fail-open: an absent verdict is missing data, and scoring it as a
            // success would quietly bias the rate downward every time the judge times out.
            CoverageMonitor monitor = monitor(0);
            for (int i = 0; i < 50; i++) {
                monitor.observe(null);
            }
            assertThat(monitor.observedCount()).isZero();
            assertThat(monitor.miscoverage()).isZero();
        }
    }
}
