package com.portfolio.recall.rag;

import com.portfolio.recall.config.RecallProperties;
import com.portfolio.recall.search.RetrievedChunk;
import io.micrometer.core.instrument.MeterRegistry;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * How many passages to put in the prompt, decided per query with a coverage guarantee
 * (docs/adr/0013).
 *
 * <p>A fixed top-K is wrong in both directions at once. On a query where the reranker has
 * found one obviously-right passage, seven more are prompt tokens spent on noise — cost,
 * prefill latency, and a wider surface for the model to wander into. On an ambiguous query
 * where the scores are nearly flat, the same K quietly truncates the passage that held the
 * answer, and nothing downstream reports it.
 *
 * <p>This keeps the shortest prefix of the reranked list whose <em>exclusive</em> cumulative
 * softmax mass stays at or below a calibrated quantile. Split conformal prediction with
 * adaptive set sizes (Romano, Sesia &amp; Candès, NeurIPS 2020) makes that quantile a
 * guarantee rather than a heuristic: calibrated offline on held-out queries by
 * {@code eval/calibrate.py}, it satisfies
 *
 * <pre>P(the kept passages contain a relevant document) &gt;= 1 - alpha</pre>
 *
 * on the next query — no distributional assumption, no requirement that the reranker be
 * well calibrated, exact at any sample size.
 *
 * <p><strong>The certificate is only worth what this class's agreement with the calibrator
 * is worth.</strong> The guarantee is a property of one procedure; if serving computes a
 * different K than calibration assumed, alpha means nothing. {@code ConformalSetSizerTest}
 * pins that agreement against golden vectors generated by the Python implementation.
 *
 * <p>Disabled, or configured with no threshold, it returns {@code retrieval.top-K} and the
 * pipeline behaves exactly as before.
 */
@Component
public class ConformalSetSizer {

    private static final Logger log = LoggerFactory.getLogger(ConformalSetSizer.class);

    private final boolean enabled;
    private final double threshold;
    private final double temperature;
    private final int maxK;
    private final int fallbackK;
    private final MeterRegistry meters;

    public ConformalSetSizer(RecallProperties props, MeterRegistry meters) {
        RecallProperties.Rag.Conformal conformal = props.rag().conformal();
        this.threshold = conformal.threshold();
        this.temperature = conformal.temperature() > 0 ? conformal.temperature() : 1.0;
        this.maxK = conformal.maxK() > 0 ? conformal.maxK() : props.retrieval().topK();
        this.fallbackK = props.retrieval().topK();
        this.meters = meters;
        // A threshold outside [0, 1] is not a conservative setting, it is an unconfigured
        // one — the mass being compared is a probability. Refuse rather than silently
        // returning every candidate and calling it certified.
        this.enabled = conformal.enabled() && threshold >= 0.0 && threshold <= 1.0;
        if (conformal.enabled() && !this.enabled) {
            log.warn("Conformal set sizing disabled: threshold {} is outside [0, 1]. "
                    + "Run eval/calibrate.py to produce one.", threshold);
        }
    }

    public boolean enabled() {
        return enabled;
    }

    /** Passages to keep, in reranked order. Never zero for a non-empty candidate list. */
    public int size(List<RetrievedChunk> ranked) {
        if (ranked.isEmpty()) {
            return 0;
        }
        if (!enabled) {
            return Math.min(fallbackK, ranked.size());
        }
        double[] mass = softmax(ranked);
        int ceiling = Math.min(maxK, ranked.size());
        int kept = 0;
        double prefix = 0.0;
        for (double m : mass) {
            // Exclusive prefix: the first passage always qualifies, so the context is
            // never empty, and coverage holds exactly when the relevant passage's own
            // nonconformity score is at or below the calibrated quantile.
            if (prefix > threshold) {
                break;
            }
            kept++;
            prefix += m;
        }
        int k = Math.min(kept, ceiling);
        meters.summary("recall.rag.context.passages").record(k);
        if (kept > ceiling) {
            // The cap, not the calibration, decided — the coverage promise is bounded by
            // max-k on these queries, and that has to be visible rather than inferred.
            meters.counter("recall.rag.context.capped").increment();
        }
        return k;
    }

    /**
     * Softmax over reranker scores in ranked order.
     *
     * <p>Shifted by the maximum before exponentiating: reranker logits are unbounded, and
     * the naive form overflows on a confident hit. Softmax rather than a plain
     * normalisation because the scores can be negative.
     */
    private double[] softmax(List<RetrievedChunk> ranked) {
        double top = Double.NEGATIVE_INFINITY;
        for (RetrievedChunk chunk : ranked) {
            top = Math.max(top, chunk.score());
        }
        double[] weights = new double[ranked.size()];
        double total = 0.0;
        for (int i = 0; i < ranked.size(); i++) {
            weights[i] = Math.exp((ranked.get(i).score() - top) / temperature);
            total += weights[i];
        }
        if (total <= 0.0 || !Double.isFinite(total)) {       // degenerate scores: spread evenly
            java.util.Arrays.fill(weights, 1.0 / ranked.size());
            return weights;
        }
        for (int i = 0; i < weights.length; i++) {
            weights[i] /= total;
        }
        return weights;
    }
}
